/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "ApplicationView.h"

class ApplicationController;
class SamplerWaveformControl;

//==============================================================================
/**
*/
class GrainerAudioProcessorEditor  
	: public AudioProcessorEditor,
	  public ApplicationView,
	  public juce::Slider::Listener,
	  public juce::Button::Listener,
	  public juce::ComboBox::Listener,
	  public juce::ChangeListener
{
public:
    GrainerAudioProcessorEditor (GrainerAudioProcessor* ownerFilter);
    ~GrainerAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);

	void initialize(ApplicationController *controller);

public:
	virtual void buttonClicked (Button *button);
	virtual void buttonStateChanged (Button *button);
	virtual void sliderValueChanged (Slider *slider);
	virtual void comboBoxChanged (ComboBox *comboBoxThatHasChanged);
	virtual void changeListenerCallback (ChangeBroadcaster* source);

	virtual void setGlobalParameterValue(GlobalParameter parameter, var value);

	virtual void mouseDown(const MouseEvent &event);
	virtual void mouseDrag(const MouseEvent &event);

private:
	Slider gainSlider, speedSlider, pitchSlider;
	ToggleButton directionButton;
	TextButton selectSampleButton;
	ComboBox numSlicesComboBox;
	Label gainLabel, speedLabel, numSlicesLabel, pitchLabel, filePathLabel, filePathValueLabel;
	ApplicationController *controller;
	ScopedPointer<SamplerWaveformControl> waveform;
};


#endif  // PLUGINEDITOR_H_INCLUDED
