/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "ApplicationView.h"

class ApplicationController;

//==============================================================================
/**
*/
class GrainerAudioProcessorEditor  
	: public AudioProcessorEditor,
	  public ApplicationView
{
public:
    GrainerAudioProcessorEditor (GrainerAudioProcessor* ownerFilter);
    ~GrainerAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);

	void initialize(ApplicationController *controller);

private:
	ApplicationController *controller;
};


#endif  // PLUGINEDITOR_H_INCLUDED
