/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "ApplicationView.h"

class ApplicationController;
class SamplerWaveformControl;
class StepSequencerControl;

//==============================================================================
/**
*/
class BeatSlicerAudioProcessorEditor  
	: public AudioProcessorEditor,
	  public ApplicationView,
	  public juce::Slider::Listener,
	  public juce::Button::Listener,
	  public juce::ComboBox::Listener,
	  public juce::ChangeListener
{
public:
    BeatSlicerAudioProcessorEditor (BeatSlicerAudioProcessor* ownerFilter);
    ~BeatSlicerAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);

	void initialize(ApplicationController *controller);

public:
	virtual void buttonClicked (Button *button);
	virtual void buttonStateChanged (Button *button);
	virtual void sliderValueChanged (Slider *slider);
	virtual void comboBoxChanged (ComboBox *comboBoxThatHasChanged);
	virtual void changeListenerCallback (ChangeBroadcaster* source);

	virtual void setParameterValue(ParameterID parameter, var value);

private:
	Slider gainSlider, speedSlider, pitchSlider;
	ToggleButton directionButton;
	TextButton selectSampleButton, resetSlicesButton;
	ComboBox numSlicesComboBox, numBarsComboBox;
	Label gainLabel, speedLabel, numSlicesLabel, pitchLabel, filePathLabel, filePathValueLabel, numBarsLabel;
	ApplicationController *controller;
	ScopedPointer<SamplerWaveformControl> waveform;
	ScopedPointer<StepSequencerControl> sequencer;
};


#endif  // PLUGINEDITOR_H_INCLUDED
